name: Threads Auto Post Cronjob

on:
  workflow_dispatch: 

jobs:
  post-threads:
    runs-on: windows-latest 

    steps:
      - name: Checkout mã nguồn
        uses: actions/checkout@v3

      - name: Cài đặt môi trường Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cài đặt thư viện cần thiết
        run: |
          pip install playwright requests regex gspread oauth2client pillow pyotp pytz
          playwright install chromium

      - name: Tái tạo file credentials.json từ Secret
        shell: bash
        env:
          GCP_CREDS: ${{ secrets.GCP_CREDENTIALS }}
        run: |
          echo "$GCP_CREDS" > credentials.json

      - name: Chạy Tool Auto Post
        env:
          PYTHONIOENCODING: 'utf-8'
        run: python thread_autopost_tool.py
        
      - name: Lưu ảnh chụp màn hình khi bị lỗi
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: error-screenshots
          path: "error_logs/"
